### ISSUE TITLE
Devious PK Client missing

### ISSUE THREAD

**Issue by Fryslan** [Parabot/Missing-hooks#12]
java.lang.ClassNotFoundException: client
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.parabot.core.asm.ASMClassLoader.findClass(ASMClassLoader.java:70)
    at org.parabot.core.asm.ASMClassLoader.loadClass(ASMClassLoader.java:49)
    at org.rev317.min.Loader.fetchApplet(Loader.java:44)
    at org.parabot.core.Context.load(Context.java:167)
    at org.parabot.environment.servers.executers.ServerExecuter$1.run(ServerExecuter.java:24)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
    at org.parabot.core.Context.load(Context.java:182)
    at org.parabot.environment.servers.executers.ServerExecuter$1.run(ServerExecuter.java:24)
    at java.lang.Thread.run(Thread.java:745)

**Comment by JKetelaar** [comment]
Resolved.
