### ISSUE TITLE
missing/broken hooks #getOpenInterfaceId

### ISSUE THREAD

**Issue by Scriptss** [Parabot/Missing-hooks#17]
Script started.
java.lang.AbstractMethodError: b.getOpenInterfaceId()I
        at org.rev317.min.api.methods.Game.getOpenInterfaceId(Game.java:34)
        at iplankerv2.src.IBank.execute(IBank.java:28)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:56)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.

**Comment by JKetelaar** [comment]
Fixed. Works now!
