### ISSUE TITLE
missing/broken hooks #getInterfaceCache

### ISSUE THREAD

**Issue by Scriptss** [Parabot/Missing-hooks#18]
Script started.
java.lang.AbstractMethodError: b.getInterfaceCache()[Lorg/rev317/min/accessors/I
nterface;
        at org.rev317.min.api.methods.Inventory.getInterface(Inventory.java:59)
        at org.rev317.min.api.methods.Inventory.getCount(Inventory.java:114)
        at org.rev317.min.api.methods.Inventory.getCount(Inventory.java:79)
        at iplankerv2.src.Plank.activate(Plank.java:17)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:55)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.

**Comment by JKetelaar** [comment]
Fixed. Works now!
