### ISSUE TITLE
another one (not sure what it is)

### ISSUE THREAD

**Issue by Scriptss** [Parabot/Missing-hooks#21]
Script started.
java.lang.AbstractMethodError: b.getInterfaceCache()[Lorg/rev317/min/accessors/I
nterface;
        at org.rev317.min.api.methods.Inventory.getInterface(Inventory.java:59)
        at org.rev317.min.api.methods.Inventory.getCount(Inventory.java:114)
        at org.rev317.min.api.methods.Inventory.getCount(Inventory.java:79)
        at igoldfarm.planking.marketplace.MakePlanks.activate(MakePlanks.java:23
)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:55)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.

**Comment by JKetelaar** [comment]
Seems to be the same one as all the others.
