### ISSUE TITLE
Game.getSettings

### ISSUE THREAD

**Issue by aleksiaaa** [Parabot/Missing-hooks#22]
Will cause:

java.lang.AbstractMethodError: b.getSettings()[I
        at org.rev317.min.api.methods.Game.getSetting(Game.java:95)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Frameworks.java:56)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)

**Comment by JKetelaar** [comment]
Resolved.
