### ISSUE TITLE
Ultimate-scape #getCurrentLevel

### ISSUE THREAD

**Issue by abielen** [Parabot/Missing-hooks#24]
# getCurrentLevel in ultimate-scape is broken. Error log:

java.lang.AbstractMethodError: Client.getCurrentStats()[I
        at org.rev317.min.api.methods.Skill.getCurrentLevel(Skill.java:59)
        at Action.execute(Action.java:81)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:56)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)

**Comment by JKetelaar** [comment]
That hook is missing. Will update when found.

**Comment by JKetelaar** [comment]
Updated!

**Comment by JKetelaar** [comment]
@capslock will look into this

**Comment by JKetelaar** [comment]
== Dev Note
The hook is `cD`

**Comment by JKetelaar** [comment]
We don't seem to support UltimateScape anymore.
