### ISSUE TITLE
ikov getallsceneobjects at plane higher than 0

### ISSUE THREAD

**Issue by Scriptss** [Parabot/Missing-hooks#25]
using SceneObjects.getAllSceneObjects() seems to throw an error when your plane is >= 1

```
Script started.
java.lang.NullPointerException
        at org.rev317.min.api.methods.SceneObjects.getSceneObjectsAtTile(SceneOb
jects.java:182)
        at org.rev317.min.api.methods.SceneObjects.getAllSceneObjects(SceneObjec
ts.java:161)
        at paint.Derka.execute(Derka.java:33)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:56)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.
```

**Comment by JKetelaar** [comment]
Show me your code.

**Comment by Scriptss** [comment]
http://pastebin.com/cSwiK132

**Comment by JKetelaar** [comment]
https://github.com/Parabot/Parabot-317-API-Minified/issues/28
