### ISSUE TITLE
Game.getSettings [PKhonor]

### ISSUE THREAD

**Issue by Scriptss** [Parabot/Missing-hooks#28]
Exception in thread "Thread-84" java.lang.AbstractMethodError: pkhonor.Client.getSettings()[I
        at org.rev317.min.api.methods.Game.getSettings(Game.java:104)
        at org.parabot.environment.scripts.Script.run(Script.java:76)
        at java.lang.Thread.run(Unknown Source)

**Comment by JKetelaar** [comment]
This is solved!
