### ISSUE TITLE
pkhonor getLevel

### ISSUE THREAD

**Issue by Scriptss** [Parabot/Missing-hooks#29]
java.lang.AbstractMethodError: pkhonor.Client.getCurrentStats()[I
        at org.rev317.min.api.methods.Skill.getCurrentLevel(Skill.java:59)
        at org.rev317.min.api.methods.Skill.getLevel(Skill.java:158)
        at pdragons.strategies.combat.EatFood.activate(EatFood.java:23)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:55)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.

**Comment by Scriptss** [comment]
resolved
