### ISSUE TITLE
Simplicity rsps getLevel

### ISSUE THREAD

**Issue by Reportin** [Parabot/Missing-hooks#33]
java.lang.AbstractMethodError: com.simplicity.Client.getCurrentStats()[I
	at org.rev317.min.api.methods.Skill.getCurrentLevel(Skill.java:59)
	at org.rev317.min.api.methods.Skill.getLevel(Skill.java:158)
	at SimpTrainer.Tasks.Test.execute(Test.java:21)
	at org.parabot.environment.scripts.framework.StrategyWorker.execute(Frameworks.java:56)
	at org.parabot.environment.scripts.Script.run(Script.java:112)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SandroCoutinho** [comment]
```
        <add>
            <accessor>Client</accessor>
            <field>dZ</field>
            <methodname>getCurrentStats</methodname>
            <descfield>[I</descfield>
        </add>
```

```
        <add>
            <accessor>Client</accessor>
            <field>w</field>
            <methodname>getSettings</methodname>
            <descfield>[I</descfield>
        </add>
```

```
        <add>
            <accessor>Client</accessor>
            <methodname>a</methodname>
            <desc>(Ljava/lang/String;ILjava/lang/String;)V</desc>
            <callclass>org/rev317/min/callback/MessageCallback</callclass>
            <callmethod>messageListenerHook</callmethod>
            <calldesc>(ILjava/lang/String;Ljava/lang/String;)V</calldesc>
            <callargs>1,2,0</callargs>
        </add>
```

```
        <add>
            <accessor>Interface</accessor>
            <field>V</field>
            <methodname>getMessage</methodname>
            <descfield>Ljava/lang/String;</descfield>
        </add>
```

This includes all the missing hooks for Simplicity.
