### ISSUE TITLE
PKHonor missing hook

### ISSUE THREAD

**Issue by BeauJames** [Parabot/Missing-hooks#4]
Skill.getCurrentLevel(Skill.HITPOINTS.getIndex()) seems to be missing for all. Would really appreciate it if you could find these.

E:\Parabot>cd ./

E:\Parabot>java -jar Parabot.jar -loadlocal
Checking for cache updates
Done checking cache updates.
Script started.
java.lang.AbstractMethodError: pkhonor.Client.getCurrentStats()[I
        at org.rev317.min.api.methods.Skill.getCurrentLevel(Skill.java:59)
        at iFrostDragons.Prayer.execute(Prayer.java:22)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:56)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.

**Comment by JKetelaar** [comment]
Added!
