### ISSUE TITLE
Ultimatescape  still wont load

### ISSUE THREAD

**Issue by jacakeus** [Parabot/Missing-hooks#8]
Getting same issue as with the one from near reality starts to load but then says "connection error attempting to reconnect"  tried  going to /users/you/documents/parabot/cashe to delete the cashe also ran the 
java -jar parabot.jar -clearcache

here is what cmd gave me

C:\Users\Jacques\Desktop\New folder (5)>java -jar parabot.jar -clearcache
java.io.FileNotFoundException: http://bot.parabot.org/hooks/carmeuses/ultimatesc
ape_hooks.xml&extended=true
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown S
ource)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce)
        at org.parabot.environment.api.utils.WebUtil.getInputStream(WebUtil.java
:128)
        at org.parabot.core.asm.hooks.HookFile.getInputStream(HookFile.java:37)
        at org.parabot.core.parsers.hooks.XMLHookParser.<init>(XMLHookParser.jav
a:37)
        at org.parabot.core.asm.hooks.HookFile.getParser(HookFile.java:43)
        at org.parabot.environment.servers.ServerProvider.injectHooks(ServerProv
ider.java:74)
        at org.rev317.min.Loader.injectHooks(Loader.java:73)
        at org.parabot.core.Context.load(Context.java:159)
        at org.parabot.environment.servers.executers.ServerExecuter$1.run(Server
Executer.java:24)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoSuchMethodError: org.parabot.core.network.NetworkInterface.getNetwor
kInterfaces()Ljava/util/Enumeration;
        at L.b(Unknown Source)
        at L.<clinit>(Unknown Source)
        at Client.init(Unknown Source)
        at org.parabot.core.Context.load(Context.java:186)
        at org.parabot.environment.servers.executers.ServerExecuter$1.run(Server
Executer.java:24)
        at java.lang.Thread.run(Unknown Source)

**Comment by Fryslan** [comment]
The Hookfile is located in the wrong place.

**Comment by JKetelaar** [comment]
Resolved.
