### ISSUE TITLE
Near Reality SceneObjects.interact

### ISSUE THREAD

**Issue by Kozs** [Parabot/Missing-hooks#9]
Interacting does not seem to be working on near reality.

**Comment by JKetelaar** [comment]
Any errors?

**Comment by Kozs** [comment]
java.lang.ArrayIndexOutOfBoundsException: 116
        at org.nr.client.a.m.f(a:879)
        at org.nr.client.Client.f(kh:12403)
        at org.nr.client.Client.D(kh:4729)
        at org.nr.client.Client.doAction(kh)
        at org.rev317.min.api.methods.Menu.sendAction(Menu.java:265)
        at org.rev317.min.api.methods.Menu.sendAction(Menu.java:236)
        at org.rev317.min.api.methods.Menu.sendAction(Menu.java:223)
        at org.Kozs.parabot.NR.kRocktail.Main$Banking.execute(Main.java:74)
        at org.parabot.environment.scripts.framework.StrategyWorker.execute(Fram
eworks.java:56)
        at org.parabot.environment.scripts.Script.run(Script.java:111)
        at java.lang.Thread.run(Unknown Source)
Script stopped.

**Comment by JKetelaar** [comment]
Seems to be a script issue. Could you post the code you use to interact?

**Comment by Kozs** [comment]
SceneObject Booth = SceneObjects.getClosest(2213);
                        Menu.sendAction(502, 502, Booth.getHash(), 50);

I've also done

SceneObject Booth[] = SceneObjects.getClosest(2213);

Booth[0].interact(0);

**Comment by JKetelaar** [comment]
Use a for loop to interact and see if any sceneobjects available. Please reply if it didn't work or not.

**Comment by Kozs** [comment]
This might be more useful

I click the booth, the CMD prints this..

[index: 13, action1: 502, action2: 1110006065, action3: 50, id: 502]

Then the bot clicks the booth. 

[index: 1, action1: 502, action2: 1110006065, action3: 50, id: 502]

(Doesnt open bank)

**Comment by Fryslan** [comment]
The action1 and id hooks have the same field in hookfile wich is an problem.

**Comment by JKetelaar** [comment]
What are the correct ones?

**Comment by Fryslan** [comment]
cant find it sorry.

**Comment by JKetelaar** [comment]
Resolved.
